### ISSUE TITLE
Bug: TypeError: parse is not a function in reportSummaryTable (Commit d638476)

### ISSUE THREAD

**Issue by BarbaraGodayol** [jasp402/cypress-cucumber-report-features#3]
After the changes introduced in commit d638476, the report generator fails with the following **error**: **TypeError: parse is not a function at Object.reportSummaryTableCauseIn lib/report-generator.js**, the code attempts to destructure a parse function from the @cucumber/gherkin package:

`const { parse } = require('@cucumber/gherkin');`

However, the official @cucumber/gherkin package (v24.0.0+) does not export a top-level parse function. This results in parse being undefined, leading to the crash when it's called later in the code. Steps to reproduce:
- Use version 2.1.3 or any version including commit d638476.
- Run the report generation process. The process will crash when attempting to process any .feature file.

Suggested Fix:
To use the modern Cucumber Gherkin parser, you need to instantiate the GherkinParser class using a message ID generator. Here is a quick example of how it should be implemented:
```
const { GherkinParser } = require('@cucumber/gherkin');
const { IdGenerator } = require('@cucumber/messages');

// Initialize the parser
const uuidQuery = IdGenerator.uuid();
const parser = new GherkinParser(uuidQuery);

// Use it inside reportSummaryTable
const gherkinDocument = parser.parse(fileContent);
```
